runtimed/runtimed

- runtimelib/src/jupyter/client.rs
- runtimelib/src/jupyter/messaging.rs
Made some functions public and added a send command.
Needing to make these functions public might mean the abstraction isn't quite
right with the runtime manager in the next PR. Though I think it's still a big
improvement.
We will have a route that constructs a JupyterMessage to send on mpsc channel
to the client. We have the route do this because it needs to return the
parent_message_id to the client. We don't have a request/response mechanism
here yet, just a one way channel.
> Runtime lib updates for channel/attach support

- runt/src/main.rs
`Message: Event {
event: "message",
data: "{\"header\":{\"date\":\"2024-03-07T20:10:49.556959Z\",\"msg_id\":\"871b07ef-7e6b76354105ad4ad6a63192_22411_173\",\"msg_type\":\"status\",\"session\":\"871b07ef-7e6b76354105ad4ad6a63192\",\"username\":\"blazzy\",\"version\":\"5.3\"},\"parent_header\":{\"date\":\"2024-03-07T20:10:49.538724Z\",\"msg_id\":\"ca77fa0d-e423-4a5b-bb64-1654498cf645\",\"msg_type\":\"execute_request\",\"session\":\"2bc4eb83-3c2a-4f00-8fae-4285df90b4de\",\"username\":\"todo-user\",\"version\":\"5.3\"},\"metadata\":{},\"content\":{\"execution_state\":\"idle\"}}",
id: "",
retry: None,
}`
vs
`{"header":{"date":"2024-03-07T19:48:22.031596Z","msg_id":"871b07ef-7e6b76354105ad4ad6a63192_22411_168","msg_type":"status","session":"871b07ef-7e6b76354105ad4ad6a63192","username":"blazzy", …
> Make attach output a little less obnoxious

- .github/workflows/rust.yml
- runtimelib/Cargo.toml
- runtimelib/src/jupyter/mod.rs
- runtimelib/src/lib.rs
- runtimelib/src/media.rs
Some initial work on #24, adding `MimeType` and `MimeBundle`.
```rust
use runtimelib::media{MimeBundle, MimeType};
let raw = r#"{
"text/plain": "Hello, world!",
"text/html": "<h1>Hello, world!</h1>",
"application/json": {
"name": "John Doe",
"age": 30
},
"application/vnd.dataresource+json": {
"data": [
{"name": "Alice", "age": 25},
{"name": "Bob", "age": 35}
],
"schema": {
"fields": [
{"name": "name", "type": "string"},
{"name": "age", "type": "integer"}
]
}
},
"application/octet-stream": "Binary data"
}"#;
let bundle: MimeBundle = serde_json::from_str(raw).unwrap();
let richest = bundle.richest(&[MimeType::DataTable, MimeType::Json, MimeType::Html]);
let (mime_type, content) = richest.unwrap();
assert_eq!(mime_type, MimeType::DataTable);
```
I've got some stashed code for `DisplayData` …
> create structs and enums for media type data

- runt/src/main.rs
- runtimelib/src/jupyter/kernelspec.rs
- runtimelib/src/jupyter/mod.rs
- runtimelib/tests/kernels/ir/kernel.json
- runtimelib/tests/kernels/python3/kernel.json
- runtimelib/tests/kernels/rust/kernel.json
still need to fix:
- prints out the displayname and language, rather than the dirname like jupyter does
- the kernelspecs() primary interface should return the kernelspec directory in additon to the json structure
> add `runt environments`

- runt/src/main.rs
- runtimed/src/runtime_manager.rs
- runtimelib/src/jupyter/client.rs
- runtimelib/src/jupyter/discovery.rs
- runtimelib/src/lib.rs
- centralize struct creation/init as impl off struct
- separate out ConnectionInfo from JupyterRuntime
- prepare for a JupyterRuntime launch process, that will have some sort of OS process ownership, polling, etc.
This is a WIP and will need some additional cleanup, but could benefit on early comment
> Refactor ConnectionInfo out of JupyterRuntime

- runt/src/main.rs
- runtimed/src/routes.rs
- runtimelib/Cargo.toml
- runtimelib/src/jupyter/client.rs
- runtimelib/src/jupyter/kernelspec.rs
- runtimelib/src/jupyter/mod.rs
- runtimelib/tests/kernels/ir/kernel.json
`runt run kernel_name connection_file_path` will launch a new kernel, given an existing connection file, and a matching kernel_name spec in one of the Jupyter `kernels/` directories.
Kernels can be interacted with by `runt exec`, and in particular a Python kernel can be stopped with `runt exec uuid quit`.
Among the ongoing issues:
- management of the child process and cleaning up the OS-kernel process table by properly wait()ing for an exit code must be reviewed. This commit puts it into a tokio task, and returns the JoinHandle for the task. When runtimed launches a kernel it could instead capture that handle and update its state when the kernel exits
- runtimed does not pick up on new kernels except through files getting added to the directory, so `runt ps` may report incorrect results. …
> launching kernels

- runt/Cargo.toml
- runt/src/main.rs
- runtimed/Cargo.toml
- runtimed/src/execution.rs
- runtimed/src/lib.rs
- runtimed/src/main.rs
- runtimed/src/routes.rs
- runtimelib/src/jupyter/client.rs
- runtimelib/src/jupyter/mod.rs
- runtimelib/src/messaging/content.rs
- runtimelib/src/messaging/mod.rs
I'm loosening the interfaces a bit to make them be able to be used by a kernel (server), like Deno.
One of the main additions here is the `AsChildOf` trait, to make it easier to go from fully typed content to a jupyter message.
```rust
let reply = CompleteReply {
matches,
cursor_start,
cursor_end,
metadata: Default::default(),
}
.as_child_of(msg);
connection.send(reply).await?;
```
> Kernel Server Additions

- runtimed/src/execution.rs
- runtimelib/src/messaging/content.rs
- runtimelib/src/messaging/mod.rs
Switches `as_child_of` to just borrow the parent message (it will clone the parent's header).
While I was at it I also:
* Renamed `ErrorReply` to `ErrorOutput`
* Put `AsChildOf` trait on `IsCompleteReply`
> refactor(messaging): borrow parent message in `as_child_of`

- runtimed/src/execution.rs
- runtimed/src/runtime_manager.rs
- runtimelib/src/messaging/content.rs
- runtimelib/src/messaging/mod.rs
* HistoryRequests have optional fields
* StdioMsg is back as an enum
* JupyterMessage::new now takes a parent
* ZMQ Identities are cloned from the parent
Having optional fields makes me realize we probably should just have a basic default reply if for some reason we do not handle a particular request (assuming new fields, etc.).
> Address protocol issues and flexibilities

- runtimed/src/execution.rs
- runtimelib/src/media.rs
- runtimelib/src/messaging/content.rs
ExecuteResult should not have a HashMap or it should have been `HashMap<String, serde_json::Value>` at the very least. Here I've switched it over to using the fully typed MimeBundle.
> adapt ExecuteResult to using fully typed MimeBundle

- runtimed/src/routes.rs
- runtimelib/src/messaging/content.rs
Fill out the rest of HistoryReply, even though it's really only used by QtConsole and `jupyter console`.
> More fields and defaults

- runtimed/src/execution.rs
- runtimed/src/runtime_manager.rs
- runtimelib/src/messaging/content.rs
- runtimelib/src/messaging/mod.rs
- runtimelib/src/messaging/time.rs
This is a bit of an overhaul.
* Catch unknown messages into a generic struct that can be used by a client to implement handling for new message types without needing changes to this crate
* Document more of the message types
* Document the macro created `as_child_of`
* Document macro created `impl From<SomeMessageContent> for JupyterMessage`
* Include Deno's implementation of `utc_now()` to get around the inclusion of the "iana-time-zone" crate, which links to macOS's "CoreFoundation" framework (which increases startup time).
> Handle unknown message types

- runtimelib/src/messaging/content.rs
Jupyter supports the [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/) as well as a [few other notebook specific messages](https://jupyter-client.readthedocs.io/en/latest/messaging.html#debug-request).
For now, this is just a stub to be able to work with this as pure `Value`. Plenty more that could be added in to close out #89.
> include stubs for debug_* messages

- runtimelib/src/messaging/content.rs
Anything other than string or a code mirror mode object will break rendering notebooks on github and notebook viewer.
> make codemirror mode more explicit

- runt/src/main.rs
- runtimelib/src/jupyter/client.rs
- runtimelib/src/jupyter/kernelspec.rs
- runtimelib/src/jupyter/mod.rs
- runtimelib/src/lib.rs
- runtimelib/src/messaging/content.rs
- runtimelib/src/messaging/mod.rs
* Expose types for the kernel or client connections so a developer doesn't have to track down whether they need a SubSocket, PubSocket, RouterSocket, etc.
* Create helper methods for creating connections for a kernel to use
* Clean up uses of unwrap that do not belong
* Correct the metadata structure
* Include and sort the rest of the message types for `from_type_and_content`
* Streamline message -> wire protocol
> Export to messaging

- runtimed/src/runtime_manager.rs
- runtimelib/src/jupyter/client.rs
- runtimelib/src/jupyter/discovery.rs
- runtimelib/src/messaging/mod.rs
This adds helper methods to create `ZeroMQ Message <> RawMessage <> JupyterMessage`. I also exposed the client creation methods directly instead of using the big JupyterClient struct because it made it easier to work on other threads (like in Zed).
> Clean clients

- runtimelib/src/messaging/mod.rs
add a way to build on some zmq identities
> set zmq identities when using `with_parent`

- README.md
- runtimed/Cargo.toml
- runtimed/src/routes.rs
- runtimelib/Cargo.toml
- runtimelib/src/jupyter/client.rs
- runtimelib/src/jupyter/dirs.rs
- runtimelib/src/jupyter/discovery.rs
- runtimelib/src/jupyter/kernelspec.rs
- runtimelib/src/jupyter/mod.rs
- runtimelib/src/lib.rs
- runtimelib/src/media/mod.rs
- runtimelib/src/messaging/content.rs
- runtimelib/src/messaging/mod.rs
Add support for https://github.com/zed-industries/async-dispatcher.
This adds a bunch of `cfg` directives to allow working with either tokio or async dispatcher (primarily for spawning).
While testing that this was all working with a new kernel, I fixed up a few other things:
* `IsCompleteReplyStatus` enum variants are now all `snake_case`d for serde
* Provide a way to set the session ID or assume it from the caller
> Introduce async dispatcher

- runtimelib/src/messaging/content.rs
- runtimelib/src/messaging/mod.rs
* drop AsChildOf trait in favor of direct implementation
* Perform less `clone`ing
> process message content structs in one batch

- runtimelib/src/messaging/content.rs
Noticed there wasn't a way to work with these `CommId`s directly without making the interface more public.
cc @bartlomieju @manzt
> expose CommId's String type directly

- runtimelib/src/jupyter/client.rs
- runtimelib/src/messaging/content.rs
- runtimelib/src/messaging/mod.rs
I started adding `with_session` to Deno only to realize it would be far easier to have the `session_id` on the connection struct.
> Improved session on connection

- runtimed/src/runtime_manager.rs
- runtimelib/src/messaging/content.rs
- runtimelib/src/messaging/mod.rs
This PR changes the serialization behavior of `JupyterMessage` to serialize absent `parent_header`s as an empty object (`{}`) instead of `null`.
This expectation is described in the Jupyter docs:
> If there is no parent, an empty dict should be used.
>
> — https://jupyter-client.readthedocs.io/en/latest/messaging.html#parent-header
I discovered when working with IJulia that it fails to parse messages when it receives a `parent_header` that is `null`.
> Serialize absent `parent_header` as an empty object

- runtimelib/src/messaging/content.rs
This PR changes the serialization behavior of `ExecuteRequest`  to serialize absent `user_expressions`s as an empty object (`{}`) instead of `null`.
I discovered when working with IJulia that it fails to properly handle `ExecuteRequest`s where the `user_expressions` is `null`.
> Serialize absent `user_expressions` as an empty object

- runtimelib/Cargo.toml
This PR adds the `repository` field to `runtimelib`'s `Cargo.toml`.
This makes it easier to get to the repository from crates.io.
> Add `repository` field to `runtimelib`'s Cargo manifest

- Cargo.toml
- jupyter-web/Cargo.toml
- jupyter-web/src/client.rs
- jupyter-web/src/main.rs
- jupyter-web/src/websocket.rs
- runtimelib/README.md
- runtimelib/src/messaging/mod.rs
* Support connecting to Jupyter servers via websockets using the strongly typed `JupyterMessage` type from `runtimelib`
* Handle both nbclassic and Jupyter server implementations
There's a `main.rs` here mostly just for a sanity check before doing integration work with Zed.
> create a jupyter web crate

- crates/nbformat/Cargo.toml
We don't want to opt in to any async runtimes when just using `nbformat` so I'll disable default features. We may need to just break out the protocol types. I'd call that crate `jupyter-types`, but that's already taken on crates.io.
> turn off default features for runtimelib in nbformat

- crates/nbformat/src/v4.rs
Needed `Clone` for use in Zed.
> allow cloning v4 structs

- crates/sidecar/src/static/main.js
Since Jupyter HTML output commonly relies on being able to run javascript when added to the page we need to use the Fragment API.
This allows outputs like Plotly to render properly\*. Shown here is viewing Plotly output while running code in Zed:
\* Technically I had to sideload Plotly on our routes to be loaded with `/plotly.js` but I didn't include that here.
> embed HTML using fragments, which will run JS

- crates/nbformat/src/v4.rs
Not sure if this is an API surface area you want to take on, but I was poking around with `nbformat` for juv and it would be useful.
Usage in: https://github.com/manzt/juv-rs/blob/aa250b57d49cc44a3a83bdd31281f024789f6308/Cargo.toml#L12
> Support serializing v4 notebooks

- crates/jupyter-serde/src/media/mod.rs
- crates/nbformat/src/lib.rs
- crates/nbformat/src/v4.rs
- crates/nbformat/tests/conformance.rs
- crates/sidecar/src/main.rs
Sets up a basic testing setup to start uncovering any differences between the python `nbformat` output of a notebook and ours.
Update: lots of little things got fixed up to be in full compliance between `nbformat` on crates.io and pypi.
Closes #134
> Test v4.5 serialization conformance

- crates/sidecar/src/main.rs
Loosey goosey messages interfered with `jupyter console` output.
> clean up logging and debug statements in sidecar

- Cargo.toml
- crates/sidecar/README.md
- crates/sidecar/src/main.rs
- Add release profile optimizations in Cargo.toml
- Update README with improved usage instructions
- Implement quiet mode flag in sidecar CLI
- Suppress logger initialization when quiet mode is active
> feat: Enhance sidecar performance and usability

- Cargo.toml
- crates/jupyter-serde/src/lib.rs
- crates/jupyter-websocket-client/src/client.rs
- crates/runtimelib/src/jupyter/kernelspec.rs
- crates/runtimelib/src/jupyter/mod.rs
- Move JupyterKernelspec struct to jupyter-serde crate
- Update imports and references in other crates
- Remove unused fields and dead code annotations
- Add optional 'path' field to KernelLaunchRequest
- Clean up and reorganize struct definitions
> jupyter-websocket-client: rely on jupyter-serde for kernel spec struct

- crates/jupyter-websocket-client/Cargo.toml
- crates/jupyter-websocket-client/src/client.rs
- crates/jupyter-websocket-client/src/websocket.rs
I was scratching my head at why I couldn't connect up to a mybinder instance, only to realize that I needed to:
* Enable TLS
* View the errors coming out of `connect_async` more directly
* Not use a custom `Request` (without handling additional headers)
> Enable tls

- crates/jupyter-websocket-client/src/client.rs
Some VPN configurations require that websockets present a user agent. This adds it in directly.
Verified with [`smoke`](https://github.com/runtimed/smoke) by setting this in the Cargo.toml:
```
jupyter-protocol = { git = "https://github.com/runtimed/runtimed", branch = "user-agent" }
jupyter-websocket-client = { git = "https://github.com/runtimed/runtimed", branch = "user-agent" }
```
> set a user agent for the websocket connection

- Cargo.toml
- crates/jupyter-websocket-client/Cargo.toml
- crates/jupyter-websocket-client/src/client.rs
- crates/jupyter-websocket-client/src/websocket.rs
I'd like to upgrade Zed's version of async tungstenite, and also move to the tokio
backend to avoid some "dubious" code in the async-tls backend.
To do that, I need to bump the version here (doing it with a >= so that future
version bumps are easier) and also switch out the feature flags (because Rust
unions all feature flags...)
c.f. https://github.com/rustls/rustls/issues/2316#issuecomment-2662838186
> Bump async-tungstenite

- .github/workflows/clippy.yml
- .github/workflows/linux.yml
- .github/workflows/windows.yml
- crates/runtimelib/Cargo.toml
- rust-toolchain.toml
Uses https://github.com/dsherret/rust-toolchain-file to ensure a 
consistent version of Rust is used in CI.
> ci: use dsherret/rust-toolchain-file action

- .github/workflows/clippy.yml
- crates/ollama-kernel/Cargo.toml
- crates/runt/Cargo.toml
- crates/runtimelib/Cargo.toml
- crates/runtimelib/src/connection.rs
- crates/sidecar/Cargo.toml
_ring_ is unmaintained https://rustsec.org/advisories/RUSTSEC-2025-0007.html. [aws-lc-rs](https://github.com/aws/aws-lc-rs) is a ring-compatible cryptography crate. 
This PR adds a feature flag that enables runtimelib to be built using aws-lc-rs instead of ring.
> runtimelib: add `aws-lc-rs` feature

- crates/jupyter-protocol/src/messaging.rs
I am getting an error in my code:
Error deserializing content for msg_type `status`: unknown variant `starting`, expected `busy` or `idle`
This occurs in my project when there is not yet a connection and i want to do a executeRequest it first creates a connection and then directly do the execute request. I would really like to act on the executionState instead of a deserializing error :)
> Add missing starting/restarting execution state

- Cargo.toml
- crates/jupyter-protocol/Cargo.toml
- crates/jupyter-protocol/src/messaging.rs
- crates/ollama-kernel/src/main.rs
I have verified and aligned the related JupyterMessage structs against the [JupyterLab repo.](https://github.com/jupyterlab/jupyterlab/blob/main/packages/services/src/kernel/messages.ts)
I noticed in some cases a ReplyStatus was expected according to some of the jupyter-protocol code but not according to JupyterLab, i was not sure what to do in this case, so i have adjusted the Rust code to use default at Serde, which i think makes the most sense to be compatible with the actual Jupyter code. But it might be i have overlooked something.
I also properly adjusted the ExecuteState code to the defintions of JupyterLab code (compared to me previous PR)
Due to the breaking changes i have already put the cargo.toml to version 0.9.0 and adjusted the ollama-kernel to the changes.
Also one of the …
> Verify jupyter message structs
