runtimed/runtimed

runt/Cargo.toml, runt/src/main.rs
The output isn't formatted very well yet. But here is an `attach` command
that now interacts with runtimed.
I was a little sad SSE support wasn't built into the reqwest library.
=> Attach command in CLI

runtimed/src/main.rs, runtimed/src/runtime_manager.rs, runtimelib/src/jupyter/dirs.rs, runtimelib/src/jupyter/discovery.rs
Just to make my other changes in upcoming PRs clean, I ran `cargo fmt`.
cc @blazzy
=> run `cargo fmt` on the code base

runt/src/main.rs, runtimed/src/db.rs, runtimed/src/runtime_manager.rs, runtimelib/src/jupyter/client.rs, runtimelib/src/jupyter/dirs.rs, runtimelib/src/lib.rs
Running `cargo clippy` and cleaning up along the way.
=> Clippy athon

runtimelib/src/messaging/content.rs
Implement the `comm_info_request`/`reply` messages.
=> implement comm-info-request, reply

.github/workflows/windows.yml, runtimelib/src/jupyter/client.rs
=> runtimelib: add support for windows

runtimelib/src/messaging/content.rs
* implement `InspectReply` & `InspectRequest`
* expand metadata support
=> implement InspectReply & InspectRequest

runtimelib/src/messaging/mod.rs
Closes https://github.com/runtimed/runtimed/issues/97
=> refactor: Add JupyterMessage::{with_metadata, with_buffer, with_parent}

runtimed/src/execution.rs, runtimelib/src/media.rs, runtimelib/src/media/datatable.rs, runtimelib/src/media/mod.rs
=> capture media type values on enum

runtimelib/src/media/mod.rs, runtimelib/src/messaging/content.rs
* implement payloads
* implement From inner message struct to enum
* additional tests to ensure custom serialization and deserialization is compliant
* fix mimebundle serialization
* process defaults for transient data more simply
=> additional conveniences and structs

runtimelib/src/messaging/content.rs
Surprised I missed this message.
=> include the `clear_output` message

crates/jupyter-websocket-client/Cargo.toml, crates/nbformat/Cargo.toml, crates/runtimelib/Cargo.toml, crates/runtimelib/README.md, crates/runtimelib/src/media/mod.rs
Noticed that `TabularDataResource` was making the enum hefty via https://github.com/runtimed/runtimed/actions/runs/11543729182/job/32128457249.
=> Box up tabular data resource

crates/runtimelib/Cargo.toml, crates/runtimelib/src/messaging/mod.rs, crates/sidecar/Cargo.toml, crates/sidecar/deno.json, crates/sidecar/src/main.rs, crates/sidecar/src/static/index.html, crates/sidecar/src/static/main.js, crates/sidecar/src/static/types.ts
Geting close!
but still some open-ends:
- ~Binary data with isn't working.~ EDIT: Binary data is working with the commented out HMAC stuff in the jupyter message decoding.
- I _think_  I'm sending messaging back from the client to event loop... but they don't seem to be being dispatched correctly with the `shell`. That is, linking widgets on the Python side isn’t working.
=> sidecar widgets

crates/jupyter-serde/src/media/datatable.rs, crates/nbformat/src/v4.rs, crates/nbformat/tests/conformance.rs, crates/nbformat/tests/notebooks/Mediatypes.ipynb, crates/nbformat/tests/notebooks/News_Categorization_MNB 10-oct-2017.ipynb
Added more notebooks for testing and uncovered more issues.
=> More notebooks

crates/jupyter-serde/src/media/mod.rs, crates/runtimelib/src/messaging/content.rs
Just a simple addition of `From<Vec<MediaType>>` and some more use of `.into()`.
=> Convert Vec<MediaType> to Media in place

crates/jupyter-serde/src/media/mod.rs, crates/nbformat/tests/conformance.rs
One more test case and handling of `MediaType::Other`.
=> process `Other` media types as is

Cargo.toml, crates/jupyter-serde/Cargo.toml, crates/jupyter-websocket-client/Cargo.toml, crates/nbformat/Cargo.toml, crates/runtimelib/Cargo.toml, crates/sidecar/Cargo.toml
Bubble up deps and loosen them up for users.
=> Workspace deps

.github/workflows/clippy.yml, .github/workflows/linux.yml, Cargo.toml, crates/ollama-kernel/Cargo.toml, crates/ollama-kernel/src/main.rs, crates/ollama-kernel/src/ollama_client.rs, crates/ollama-kernel/src/structured_calling.rs
This adds an experimental Ollama kernel. I made it partially for fun and partially to have a kernel in this repository for making sure runtimelib (and related packages) were in a good state.
=> create an ollama kernel

crates/jupyter-protocol/README.md, crates/jupyter-protocol/src/messaging.rs, crates/jupyter-serde/README.md, crates/jupyter-serde/src/lib.rs, crates/nbformat/README.md, crates/ollama-kernel/Cargo.toml, crates/ollama-kernel/src/main.rs, crates/sidecar/README.md, crates/sidecar/deno.json
Write up more README content in prep for publishing.
=> More readmes, import utilities

.github/workflows/clippy.yml, Cargo.toml, crates/mybinder/Cargo.toml, crates/mybinder/fixtures/failed-launch, crates/mybinder/fixtures/success-launch, crates/mybinder/src/lib.rs
This adds an enum and a function for parsing the mybinder build API. Slated to work alongside the jupyter websocket client.
=> Package for mybinder builds

crates/jupyter-websocket-client/Cargo.toml
=> bump async tungstenite

crates/jupyter-protocol/src/messaging.rs
Noticed that #171 was failing for spurious reasons. This should fix it up.
=> remove extraneous whitespace

crates/jupyter-protocol/src/lib.rs
=> expose `Transport` at the `jupyter-protocol` level

crates/sidecar/Cargo.toml, crates/sidecar/src/main.rs
Bumps wry and tao to their latest versions. The breaking changes for wry were introduced in `v0.46.0`.
=> Bump wry and tao

Cargo.toml, crates/jupyter-serde/Cargo.toml, crates/jupyter-websocket-client/Cargo.toml, crates/nbformat/Cargo.toml, crates/ollama-kernel/Cargo.toml, crates/runt/Cargo.toml, crates/runt/src/main.rs, crates/runtimelib/Cargo.toml, crates/sidecar/Cargo.toml
Bringing `runt` back, starting with `runt ps`. More to come.
=> Bringing the Runt CLI back

crates/jupyter-protocol/src/messaging.rs
i created an issue regarding deserializing JupyterMessage https://github.com/runtimed/runtimed/issues/184
This is the fix to deserialize also "parent_header": {}
Also added 2 tests to check if it's working.
=> Fix deserializing "parent_header": {}
